version: "3.9"
services:
  json-server:
    image: irensaltali/json-server
    volumes:
      - ./json-data:/json-server
    ports:
      - "5001:3000"

  mock-server:
    image: irensaltali/wiremock
    volumes:
      - ./mappings:/wiremock/mappings
    ports:
      - "5000:5000"
    links:
      - "jsonserver:json-server"
    depends_on:
      - json-server